FROM apache/airflow:2.8.1-python3.9

USER airflow

RUN pip install --no-cache-dir mlflow scikit-learn pandas optuna catboost optuna-integration[sklearn]
RUN pip install apache-airflow-providers-postgres

