FROM python:3.9-slim

RUN pip install --no-cache-dir mlflow psycopg2-binary

WORKDIR /app

COPY ./mlflow /app

CMD ["mlflow", "server", \
     "--backend-store-uri", "postgresql://airflow:airflow@postgres-mlflow:5432/mlflow", \
     "--default-artifact-root", "/mlflow/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"]